---
jobs:
  - name: sample-job
    displayName: A sample Job
    description: possibly the best sample job
    git:
      enabled: true
      remoteName: "origin"
      remoteURL: "git@github.com/bar/foo.git"
      jenkinsCredentialsID: "foobar"
      branches: "*/master"
