---
jobs:
  # A minimal job
  - name: sample-job
    git:
      enabled: true
      remoteName: "origin"
      remoteURL: "git@github.com/bar/foo.git"
      jenkinsCredentialsID: "foobar"
      branches: "*/master"

  # A more advanced job
  - name: advanced-job
    displayName: A bigger job
    description: Possibly the best job in the world
    git:
      enabled: true
      remoteName: "origin"
      remoteURL: "git@github.com/bar/foo.git"
      jenkinsCredentialsID: "foobar"
      branches: "*/master"
    triggers:
      scmPolling:
        enabled: true
        schedule: "H * * * *"
        ingorePostCommitHooks: false
      Timer:
        enabled: true
        schedule: "H 2 * * *"
